apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.19.4
      helm:
        valueFiles:
          - $my-git/apps/cilium/values.yaml

    - repoURL: https://github.com/Andrea92Fabio/Cluster-Local.git
      targetRevision: HEAD
      ref: my-git

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
