apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"  

nodes:
- role: control-plane
  image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
  extraMounts:
    - hostPath: ./
      containerPath: /apps

- role: worker
  image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
  extraPortMappings:
  - containerPort: 30080 
    hostPort: 80         
    protocol: TCP
  - containerPort: 30443 
    hostPort: 443        
    protocol: TCP
  extraMounts:
    - hostPath: ./
      containerPath: /apps
    - hostPath: ./data/worker1
      containerPath: /var/lib/longhorn

# # Worker 2: Necessario per il quorum/replica di Longhorn
# - role: worker
#   image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
#   extraMounts:
#   - hostPath: ./data/worker2
#     containerPath: /var/lib/longhorn

# # Worker 3: Necessario per il quorum/replica di Longhorn
# - role: worker
#   image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
#   extraMounts:
#   - hostPath: ./data/worker3
#     containerPath: /var/lib/longhorn
