apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Spazio dove risiede il controller di Argo
  source:
    repoURL: https://github.com/Andrea92Fabio/Cluster-Local.git
    targetRevision: HEAD
    path: apps # Assicurati che i tool siano dentro questa cartella nel repository!
    directory:
      recurse: true
      include: '**/application.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
