apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  sources:
    - repoURL: https://chart.external-secrets.io
      chart: external-secrets
      targetRevision: 0.9.11
      ref: chart-ufficiale
    - repoURL: https://github.com/AndreaFabioGrossi/Cluster-Local.git
      targetRevision: HEAD
      path: apps/external-secrets
      helm:
        valueFiles:
          - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true 
    