replicaCount: 1

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

# Ottimizzazione degli helper interni
webhook:
  create: true
  replicaCount: 1
  resources:
    limits:
      memory: "64Mi"

certController:
  create: true
  replicaCount: 1
  resources:
    limits:
      memory: "64Mi"
