apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 58.2.2
      ref: chart-ufficiale
    - repoURL: https://github.com/Andrea92Fabio/Cluster-Local.git
      targetRevision: HEAD
      path: apps/monitoring
      helm:
        valueFiles:
          - values.yaml
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
