# Forza Longhorn a non cercare altri nodi per replicare i dati
defaultSettings:
  defaultReplicaCount: 1
  replicaSoftAntiAffinity: true
  storageMinimalAvailablePercentage: 15

# Ottimizzazione delle risorse per i componenti interni (ridotte al minimo indispensabile)
longhornManager:
  resources:
    limits:
      memory: "256Mi"
longhornDriver:
  resources:
    limits:
      memory: "128Mi"

# Ingress per accedere alla UI di Longhorn dal browser
ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.local
  path: /
