apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.15.0
      ref: chart-ufficiale
    - repoURL: https://github.com/Andrea92Fabio/Cluster-Local.git
      targetRevision: HEAD
      path: apps/sealed-secrets
      helm:
        valueFiles:
          - values.yaml 
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
