resources:
  requests:
    cpu: "10m"
    memory: "48Mi"
  limits:
    cpu: "100m"
    memory: "96Mi"

# Definisce il nome del controller che userai dalla CLI (kubeseal)
fullnameOverride: sealed-secrets-controller
