service:
  type: NodePort
  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443

deployment:
  replicas: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

# Ottimizzazione Dashboard e Sicurezza Locale
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.local`)
    entryPoints: ["web"]

providers:
  kubernetesIngress:
    publishedService:
      enabled: true
