global:
  secure: false

server:
  extraArgs:
    - --insecure

  # Configurazione Ingress per Traefik
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.local
    path: /
    pathType: Prefix
