expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.local
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web

externalURL: http://harbor.local

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: longhorn
      size: 10Gi
    chartmuseum:
      storageClass: longhorn
      size: 5Gi
    jobservice:
      storageClass: longhorn
      size: 1Gi
    database:
      storageClass: longhorn
      size: 2Gi
    redis:
      storageClass: longhorn
      size: 1Gi

portal:
  replicaCount: 1
core:
  replicaCount: 1
jobservice:
  replicaCount: 1
registry:
  registry:
    replicaCount: 1
chartmuseum:
  replicaCount: 1

# Ottimizzazione e contenimento risorse per i pod interni
database:
  internal:
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
redis:
  internal:
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
