apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-managed
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: oci://ghcr.io/argoproj/argo-helm
      chart: argo-cd
      targetRevision: 7.3.11
      helm:
        valueFiles:
          - $my-git/apps/argocd/values.yaml
    - repoURL: https://github.com/Andrea92Fabio/Cluster-Local.git
      targetRevision: HEAD
      ref: my-git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
