global:
  logging:
    level: info

server:
  replicas: 1
  extraArgs:
    - --insecure

  service:
    type: ClusterIP

repoServer:
  replicas: 1

controller:
  replicas: 1

redis:
  enabled: true

  secretInit:
    enabled: false

configs:
  cm:
    resource.customizations.ignoreDifferences.apps_DaemonSet: |
      jqPathExpressions:
        - .spec.template.spec.securityContext.appArmorProfile
